INSERT INTO USERS (USERID, LOGIN, FIRSTNAME, LASTNAME, STATUS) VALUES (-1, 'artursku', 'Arturs', 'Kurms', 'VISITOR');
INSERT INTO PASSWORDS (ID, PASSWORD1, PASSWORD2, PASSWORD3) VALUES (-1, 'arturm87s6ursku', 'urm87s6', 'Artururm87s6s');
INSERT INTO SESSIONS (SESSION_ID, USER_ID) VALUES ('node0gyvr2y9yp3olcjyjjifymxzk0', -1);